# Generated by Django 3.1.6 on 2023-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200725_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
