# Generated by Django 3.1.6 on 2023-01-03 15:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200903_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='delivery',
            new_name='delivery_time',
        ),
    ]
