# Generated by Django 3.1.6 on 2023-01-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
    ]
