# Generated by Django 3.1.6 on 2023-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200918_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
