# Generated by Django 3.1.6 on 2023-02-04 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='user_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
